## YAML Template.
---
name: Settler
main: com.mahn42.anhalter42.settler.SettlerPlugin
version: 0.11
depend: [MAHN42-Framework]
softdepend: [dynmap]
commands:
   s_list_professions:
      description: list profesions for settlers
      usage: /s_list_professions
      permission: s.list_professions
      permission-message: You don't have permission
   s_list:
      description: list settlers
      usage: /s_list
      aliases: [slist]
      permission: s.list
      permission-message: You don't have permission
   s_test:
      description: only for testing
      usage: /s_test ...
      permission: s.test
      permission-message: You don't have permission
permissions:
    s.*:
        description: Gives access to all settler commands
        children:
            s.list_professions: true
            s.test: true
            s.list: true
    s.list:
        description: Allows you to list settlers
        default: true
    s.list_professions:
        description: Allows you to list profesions for settlers
        default: true
    s.test:
        description: Allows you to test something for settlers
        default: false
      